puts "The students of my cohort at Makers Acadmemy"
puts "_ _ _ _ _ _ _ _ _ _ _ _ _ _"
puts "Shan Hasan"
puts "Ben"
puts "Graham"
puts "Stacy"
puts "Monika"
puts "Bob"
puts "Jonty"
puts "George"
puts "Jack
"